---
# coverage
modules:
  - logrotate
  - properties
  - scm
  - assignednode
  - trigger_pollscm
  - builders
  - publishers

main:
  name: '@NAME@-coverage'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@

trigger:
  pollscm: '*/15 * * * *'

builders:
  - coverage

post_build_actions:
  - coverage

scm:
  scm: 'true'

assignednode:
  node: '@NODE@'

logrotate:
  daysToKeep: 3
  numToKeep: 20
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

---
# pep8-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publishers

main:
  name: 'gate-@NAME@-pep8'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: @DISABLED@
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - pep8

post_build_actions:
  - pep8

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# python26-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publishers

main:
  name: 'gate-@NAME@-python26'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: @DISABLED@
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - python26

post_build_actions:
  - junit:
      results: '**/nosetests.xml'

scm:
  scm: 'false'

# >= precise does not have python2.6
assignednode:
  node: 'oneiric'

---
# python27-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publishers

main:
  name: 'gate-@NAME@-python27'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: @DISABLED@
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - python27

post_build_actions:
  - junit:
      results: '**/nosetests.xml'

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# docs
modules:
  - properties
  - scm
  - assignednode
  - trigger_pollscm
  - builders
  - publishers

main:
  name: '@NAME@-docs'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@

trigger:
  pollscm: '*/15 * * * *'

builders:
  - docs

post_build_actions:
  - ftp:
      site: '@DOC_PUBLISHER_SITE@'
      remote_dir: 'developer/@NAME@'
      source_files: 'doc/build/html/**'
      remove_prefix: 'doc/build/html'
      excludes: ''

scm:
  scm: 'true'

assignednode:
  node: '@NODE@'

---
# merge-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publishers

main:
  name: 'gate-@NAME@-merge'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: @DISABLED@
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# ppa
modules:
  - properties
  - scm
  - assignednode
  - trigger_none
  - builders
  - publishers

main:
  name: '@NAME@-ppa'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: true

builders:
  - ppa

post_build_actions:
  - ppa

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# tarball
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publishers

main:
  name: '@NAME@-tarball'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBulid: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_REFNAME
    type: string
    description: Zuul provided ref name
  - name: GERRIT_OLDREV
    type: string
    description: Zuul provided old reference for ref-updated
  - name: GERRIT_NEWREV
    type: string
    description: Zuul provided new reference for ref-updated

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - tarball

post_build_actions:
  - tarball:
      site: '@PUBLISHER_SITE@'

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'
