---
# coverage
main:
  name: '@NAME@-coverage'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul_post

builders:
  - gerrit_git_prep
  - coverage

post_build_actions:
  - coverage

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# pep8-gate
main:
  name: 'gate-@NAME@-pep8'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - pep8

post_build_actions:
  - pep8

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# python26-gate
main:
  name: 'gate-@NAME@-python26'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - python26

post_build_actions:
  - junit:
      results: '**/nosetests.xml'

scm:
  scm: 'false'

# >= precise does not have python2.6
assignednode:
  node: 'oneiric'

---
# python27-gate
main:
  name: 'gate-@NAME@-python27'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - python27

post_build_actions:
  - junit:
      results: '**/nosetests.xml'

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# docs
main:
  name: '@NAME@-docs'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

triggers:
  - zuul_post

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

builders:
  - gerrit_git_prep
  - docs

post_build_actions:
  - ftp:
      site: '@DOC_PUBLISHER_SITE@'
      remote_dir: 'developer/@NAME@'
      source_files: 'doc/build/html/**'
      remove_prefix: 'doc/build/html'
      excludes: ''

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# merge-gate
main:
  name: 'gate-@NAME@-merge'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# docs-gate
main:
  name: 'gate-@NAME@-docs'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - docs

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# tarball
main:
  name: '@NAME@-tarball'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBulid: 'false'
  disabled: @DISABLED@
  concurrent: 'true'

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

triggers:
  - zuul_post

builders:
  - gerrit_git_prep
  - tarball

post_build_actions:
  - tarball:
      site: '@PUBLISHER_SITE@'
      project: '@TARBALL_PROJECT@'

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'
