---
# coverage
modules:
  - logrotate
  - properties
  - scm
  - assignednode
  - trigger_pollscm
  - builders
  - publisher_coverage

main:
  name: '@NAME@-coverage'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: '@DISABLED@' 

trigger:
  pollscm: '*/15 * * * *'

builders:
  - coverage

scm:
  scm: 'true'

assignednode:
  node: '@NODE@'

logrotate:
  daysToKeep: 3
  numToKeep: 20
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

---
# pep8-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_pep8

main:
  name: 'gate-@NAME@-pep8'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: '@DISABLED@'
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - pep8

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# python26-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_junit

main:
  name: 'gate-@NAME@-python26'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: '@DISABLED@'
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - python26

scm:
  scm: 'false'

# >= precise does not have python2.6
assignednode:
  node: 'oneiric'

publisher:
  results: '**/nosetests.xml'

---
# python27-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_junit

main:
  name: 'gate-@NAME@-python27'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: '@DISABLED@'
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - python27

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

publisher:
  results: '**/nosetests.xml'

---
# docs
modules:
  - properties
  - scm
  - assignednode
  - trigger_pollscm
  - builders
  - publisher_docs

main:
  name: '@NAME@-docs'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: '@DISABLED@'

trigger:
  pollscm: '*/15 * * * *'

builders:
  - docs

scm:
  scm: 'true'

assignednode:
  node: '@NODE@'

publisher:
  site: '@PUBLISHER_SITE@'

---
# merge-gate
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_none

main:
  name: 'gate-@NAME@-merge'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: '@DISABLED@'
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_BRANCH
    type: string
    description: Zuul provided branch name
  - name: GERRIT_CHANGES
    type: string
    description: Zuul provided list of dependent changes to merge

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# ppa
modules:
  - properties
  - scm
  - assignednode
  - trigger_none
  - builders
  - publisher_ppa

main:
  name: '@NAME@-ppa'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'false'
  disabled: 'true'

builders:
  - ppa

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# tarball
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_tarball

main:
  name: '@NAME@-tarball'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBulid: 'false'
  disabled: '@DISABLED@'
  concurrent: 'true'

parameters:
  - name: UUID
    type: string
    description: Zuul provided key to link builds with Gerrit events
  - name: GERRIT_PROJECT
    type: string
    description: Zuul provided project name
  - name: GERRIT_REFNAME
    type: string
    description: Zuul provided ref name
  - name: GERRIT_OLDREV
    type: string
    description: Zuul provided old reference for ref-updated
  - name: GERRIT_NEWREV
    type: string
    description: Zuul provided new reference for ref-updated

notification_endpoints:
  - protocol: HTTP
    URL: http://127.0.0.1:8001/jenkins_endpoint

builders:
  - gerrit_git_prep
  - tarball

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

publisher:
  site: '@PUBLISHER_SITE@'


---
# pep8-check
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_pep8

main:
  name: 'check-@NAME@-pep8'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: 'true'
  concurrent: 'true'

builders:
  - gerrit_git_prep
  - pep8

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

---
# python26-check
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_junit

main:
  name: 'check-@NAME@-python26'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: 'true'
  concurrent: 'true'

builders:
  - gerrit_git_prep
  - python26

scm:
  scm: 'false'

# >= precise does not have python2.6
assignednode:
  node: 'oneiric'

publisher:
  results: '**/nosetests.xml'

---
# python27-check
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_junit

main:
  name: 'check-@NAME@-python27'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: 'true'
  concurrent: 'true'

builders:
  - gerrit_git_prep
  - python27

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'

publisher:
  results: '**/nosetests.xml'

---
# merge-check
modules:
  - properties
  - scm
  - assignednode
  - builders
  - publisher_none

main:
  name: 'check-@NAME@-merge'
  review_site: '@REVIEW_SITE@'
  github_org: '@GITHUB_ORG@'
  project: '@NAME@'
  authenticatedBuild: 'true'
  disabled: 'true'
  concurrent: 'true'

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: '@NODE@'


