---
# gate-gerrit-merge
main:
  name: 'gate-gerrit-merge'
  github_org: 'openstack-ci'
  review_site: 'review.openstack.org'
  project: 'gerrit'
  authenticatedBuild: 'true'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# check-gerrit-unittests
main:
  name: 'check-gerrit-unittests'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'gerrit'
  authenticatedBuild: 'true'
  concurrent: 'true'

triggers:
  - zuul

prebuilders:
  - gerrit_git_prep
  - gerrit_preclean

maven:
  root_module:
    group_id: com.google.gerrit
    artifact_id: gerrit-parent
  goals: 'clean package -Dgerrit.include-documentation=1 -X'

postbuilders:
  - gerrit_postrun

post_build_actions:
  - war:
      site: 'nova.openstack.org'
      warfile: 'gerrit-war/target/gerrit*.war'
      target_path: 'tarballs/ci/test/'

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# gate-gerrit-unittests
main:
  name: 'gate-gerrit-unittests'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'gerrit'
  authenticatedBuild: 'true'
  concurrent: 'true'

triggers:
  - zuul

prebuilders:
  - gerrit_git_prep
  - gerrit_preclean

maven:
  root_module:
    group_id: com.google.gerrit
    artifact_id: gerrit-parent
  goals: 'clean package -Dgerrit.include-documentation=1 -X'

postbuilders:
  - gerrit_postrun

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# gerrit-package
main:
  name: 'gerrit-package'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'gerrit'
  authenticatedBulid: 'false'
  concurrent: 'true'

triggers:
  - zuul_post

prebuilders:
  - gerrit_git_prep
  - gerrit_preclean

maven:
  root_module:
    group_id: com.google.gerrit
    artifact_id: gerrit-parent
  goals: 'clean package -Dgerrit.include-documentation=1 -X'

postbuilders:
  - gerrit_postrun

post_build_actions:
  - war:
      site: 'nova.openstack.org'
      warfile: 'gerrit-war/target/gerrit*.war'
      target_path: 'tarballs/ci/'

scm:
  scm: 'false'

assignednode:
  node: 'precise'

