---
# pyflakes-gate
main:
  name: 'gate-zuul-pyflakes'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'zuul'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - pyflakes

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# pep8-gate
main:
  name: 'gate-zuul-pep8'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'zuul'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - pep8

post_build_actions:
  - pep8

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# merge-gate
main:
  name: 'gate-zuul-merge'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'zuul'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep

scm:
  scm: 'false'

assignednode:
  node: 'precise'

