project:
  template: 'python_jobs'

values:
  name: 'zuul'
  disabled: 'false'
  github_org: 'openstack-ci'
  review_site: 'review.openstack.org'
  node: 'precise'

---
# pyflakes-gate
main:
  name: 'gate-zuul-pyflakes'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'zuul'
  concurrent: 'true'

triggers:
  - zuul

builders:
  - gerrit_git_prep
  - pyflakes

scm:
  scm: 'false'

assignednode:
  node: 'precise'

---
# zuul-docs
main:
  name: 'zuul-docs'
  review_site: 'review.openstack.org'
  github_org: 'openstack-ci'
  project: 'zuul'
  authenticatedBuild: 'false'
  concurrent: 'true'

triggers:
  - zuul_post

logrotate:
  daysToKeep: 28
  numToKeep: -1
  artifactDaysToKeep: -1
  artifactNumToKeep: -1

builders:
  - gerrit_git_prep
  - docs

post_build_actions:
  - scp:
      site: '173.203.107.207'
      source: 'doc/build/html/**/*'
      target_path: 'ci/zuul'
      keep_heirarchy: 'true'

scm:
  scm: 'false'

assignednode:
  node: 'precise'
